"""⑦ 도형 블록 12장 옛이야기(허브 확정 순서). tools/tales_build.py 가 불러 쓴다. 모두 [제안].
cast=None 이면 ③ 12장의 같은 이야기 배역표를 그대로 쓴다(tales_build.T12). 가족 악역 0·세모 웃긴 실패역 ≤3 단언은 ⑦ 세트에도 따로 적용한다."""
TB = [
 dict(base='pigs', title='아기돼지 삼형제', cast=None, cuts=[
  ('네모 엄마가 세 아이에게 벽돌 한 상자씩을 주었다. 「줄을 맞춰 쌓으면 튼튼한 집이 된단다.」', ['nemo_mom.joy', 'nemo_kids.kid1', 'nemo_kids.kid2', 'nemo_kids.kid3'], None),
  ('{kid1}와 {kid2}는 쉬운 볏짚·나무 조각으로 뚝딱뚝딱 먼저 지었다.', ['nemo_kids.kid1', 'nemo_kids.kid2'], 'sparkle'),
  ('바람 친구가 후— 불자 볏짚집과 나무집은 폴폴. {kid3}는 벽돌을 한 줄 한 줄 맞춰 쌓았다.', ['nemo_kids.kid3'], 'bang'),
  ('벽돌집은 끄떡없어 모두 모였다. 줄을 맞춘 집 한 채가 마당 가득 환했다.', ['nemo_kids.kid3', 'nemo_kids.kid1', 'nemo_kids.kid2', 'nemo_mom.love'], 'heart')]),
 dict(base='bremen', title='브레멘 음악대', cast=None, cuts=[
  ('늙었다고 쫓겨난 네 친구 — 당나귀(네모 아빠), 개(세모 남편), 고양이(세모 아내), 수탉(동그라미 아빠).', ['nemo_dad.good', 'husband.good', 'wife.good', 'dong_dad.good'], None),
  ('길 끝에 불 켜진 집이 보였지만 창문이 높았다. 네 친구는 발판 삼아 차곡차곡 쌓기로 했다.', ['nemo_dad.joy', 'husband.joy', 'wife.joy', 'dong_dad.joy'], 'question'),
  ('당나귀 위에 개, 그 위에 고양이, 그 위에 수탉. 줄 맞춘 탑이 완성되자 함께 노래했다.', ['nemo_dad.joy', 'husband.joy', 'wife.joy', 'dong_dad.joy'], 'note'),
  ('허깨비 도둑들이 놀라 달아나고, 빈집은 네 친구의 음악당이 되었다.', ['nemo_dad.love', 'husband.love', 'wife.love', 'dong_dad.warm'], 'heart')]),
 dict(base='gyeonwoo', title='견우와 직녀', origin='한국 전래동화(공유 저작물)',
  cast=[('견우', '세모 남편', 'lead', 'semo'), ('직녀', '세모 아내', 'lead', 'semo'), ('오작교를 놓는 까치와 까마귀', '까치 떼(가족 밖)', 'helper', 'outside'), ('둘을 갈라놓는 하늘 어른', '하늘 어른(가족 밖, 목소리·순한 판)', 'villain', 'outside')],
  line='은하수 양쪽에 떨어진 두 사람을 까치가 줄 잇듯 오작교로 이어 준다 — 일 년에 한 번, 환한 웃음', kept=['소 먹이는 견우와 베 짜는 직녀', '은하수로 갈라짐', '까치와 까마귀의 오작교', '칠월 칠석에 만남'],
  cuts=[('하늘나라에서 소를 키우는 견우(세모 남편)와 베를 짜는 직녀(세모 아내)가 서로 반했다. 둘은 일은 잊고 놀기만 했다.', ['husband.joy', 'wife.joy'], 'heart'),
        ('하늘 어른이 말했다. 「은하수를 사이에 두고 떨어져 지내거라.」 둘은 강 이쪽저쪽에서 손만 흔들었다.', ['husband.worry', 'wife.cry'], 'bang'),
        ('까치와 까마귀들이 날아와 날개를 이었다. 줄을 잇듯 한 칸 한 칸 오작교가 이어졌다.', ['husband.surprise', 'wife.surprise'], 'sparkle'),
        ('칠월 칠석, 두 사람은 오작교에서 만났다. 일 년에 하루지만 환하게 웃었다.', ['husband.love', 'wife.love'], 'heart')]),
 dict(base='bears', title='세 마리 곰', cast=None, cuts=[
  ('곰 세 식구(동그라미 아빠·엄마·아들)의 집엔 크기가 다른 그릇·의자·침대가 한 벌씩 줄지어 있었다.', ['dong_dad.joy'], None),
  ('길 잃은 손님(세모 아내)이 큰 것, 중간 것, 작은 것을 차례로 써 보았다. 줄 맞춰 놓인 작은 것이 딱 맞았다.', ['wife.surprise'], 'question'),
  ('큰 것은 너무 크고 중간 것은 헐렁하고 — 작은 침대에서 손님이 쿨쿨 잠이 들었다.', ['wife.tired'], None),
  ('돌아온 곰들이 깜짝! 아기 곰이 웃으며 말했다. 「같이 먹어요!」 모두 한 상에 앉았다.', ['dong_dad.warm', 'wife.joy'], 'heart')]),
 dict(base='jack', title='잭과 콩나무', cast=None, cuts=[
  ('소를 팔러 간 잭({kid2})이 마법의 콩 한 줌과 바꿔 왔다. 엄마는 한숨, 콩은 창밖으로 휙.', ['nemo_kids.kid2', 'nemo_mom.worry'], 'question'),
  ('밤새 콩나무가 한 칸 한 칸 쌓이듯 하늘까지 자랐다. 잭이 올라가 보니 구름 위에 거인의 큰 성이 있었다.', ['nemo_kids.kid2'], 'bang'),
  ('황금알을 낳는 거위를 안고 달아나는 잭. 구름 거인이 쿵쿵쿵 쫓아왔다.', ['nemo_kids.kid2'], 'sparkle'),
  ('내려온 잭이 콩나무를 베자 거인은 구름 위에서 손을 흔들었다. 세 가족이 큰 상에 모여 황금알 오믈렛을 먹었다.', ['nemo_kids.kid2', 'nemo_mom.joy', 'husband.joy', 'dong_dad.joy'], 'heart')]),
 dict(base='kongjwi', title='콩쥐팥쥐', cast=None, cuts=[
  ('깐깐한 아주머니가 콩쥐({kid1})에게 밑 빠진 독에 물을 가득 채우라고 했다.', ['nemo_kids.kid1'], 'question'),
  ('빈칸이 구멍 난 독처럼 자꾸 새었다. 두꺼비(동그라미 아빠)가 엉금엉금 나와 구멍을 막아 주었다.', ['nemo_kids.kid1', 'dong_dad.calm'], 'sparkle'),
  ('새들이 벼를 까 주었고 콩쥐는 꽃신을 신고 잔치로 달려갔다. 팥쥐({kid2})는 투덜투덜.', ['nemo_kids.kid1', 'nemo_kids.kid2'], None),
  ('꽃신 한 짝을 원님(세모 남편)이 찾아 주었다. 팥쥐도 웃으며 박수쳤다.', ['husband.joy', 'nemo_kids.kid1', 'nemo_kids.kid2'], 'heart')]),
 dict(base='heungbu', title='흥부 박', origin='한국 전래동화(공유 저작물)',
  cast=[('흥부', '네모 아빠', 'lead', 'nemo'), ('흥부 아내', '네모 엄마', 'helper', 'nemo'), ('놀부', '동그라미 아빠', 'funny', 'dong'), ('제비', '제비(art.swallow)', 'helper', 'outside')],
  line='식구 많은 흥부가 제비를 도와 박씨를 받는다, 놀부(세모 남편)는 따라 하다 풍물패가 쏟아져 함께 잔치', kept=['다친 제비를 고쳐 줌', '박씨 → 박 타기', '놀부의 따라 하기와 박'],
  cuts=[('다리를 다친 제비를 흥부(네모 아빠)가 정성껏 싸매 주었다.', ['nemo_dad.love', 'art.swallow'], 'heart'),
        ('이듬해 제비가 박씨 하나를 물어 왔다. 흥부네 식구들이 마당에 줄지어 심었다.', ['art.swallow', 'nemo_dad.joy', 'nemo_mom.joy'], None),
        ('박이 주렁주렁. 슬근슬근 톱질하자 박 속에서 쌀과 가구와 비단이 와르르!', ['art.gourd', 'nemo_dad.surprise', 'nemo_mom.joy'], 'bang'),
        ('놀부(세모 남편)도 따라 박을 탔지만 풍물패가 쏟아져 한바탕 춤판! 놀부는 웃으며 흥부네 잔치에 끼었다.', ['husband.wink', 'nemo_dad.joy', 'nemo_mom.joy'], 'sparkle')]),
 dict(base='ureng', title='우렁 각시', origin='한국 전래동화(공유 저작물)',
  cast=[('혼자 농사짓는 총각', '네모 아빠', 'lead', 'nemo'), ('우렁 각시', '세모 아내', 'helper', 'semo'), ('각시를 탐내는 원님', '욕심쟁이 원님(가족 밖, 목소리·순한 판)', 'villain', 'outside')],
  line='항아리 속 우렁에서 각시가 나와 밥상을 차려 준다. 원님은 내기에서 지고 물러난다', kept=['논에서 큰 우렁이를 얻음', '몰래 밥상을 차려 줌', '항아리에서 각시가 나옴', '원님의 욕심'],
  cuts=[('혼자 농사짓는 네모 아빠가 논에서 큰 우렁이를 주워 항아리에 넣어 두었다.', ['nemo_dad.joy'], None),
        ('다음 날부터 집에 오면 밥상이 차려져 있었다. 몰래 지켜보니 항아리에서 우렁 각시(세모 아내)가 나왔다.', ['nemo_dad.surprise', 'wife.joy'], 'question'),
        ('욕심쟁이 원님이 각시를 탐내 내기를 걸었다. 각시의 꾀로 네모 아빠가 내기에서 이겼다.', ['nemo_dad.good', 'wife.wink'], 'bang'),
        ('원님은 머쓱해져 물러났다. 두 사람은 오래오래 한집에서 밥상을 둘러앉아 살았다.', ['nemo_dad.love', 'wife.love'], 'heart')]),
 dict(base='axe', title='금도끼 은도끼', cast=None, cuts=[
  ('나무꾼 네모 아빠가 도끼를 연못에 빠뜨렸다.', ['nemo_dad.worry'], 'bang'),
  ('산신령(동그라미 아빠)이 금도끼를 들고 물었다. 「이게 네 도끼냐?」 「아닙니다.」 은도끼도 「아닙니다.」', ['dong_dad.warm', 'nemo_dad.good'], 'question'),
  ('쇠도끼가 나오자 「그건 제 것입니다.」 정직한 나무꾼은 금도끼와 은도끼까지 받았다.', ['nemo_dad.love', 'dong_dad.joy'], 'sparkle'),
  ('소문을 들은 이웃 네모 엄마가 거짓말하려다 웃음이 터져 쇠도끼만 받고 함께 웃었다.', ['nemo_mom.wink', 'dong_dad.joy', 'nemo_dad.joy'], 'heart')]),
 dict(base='ant', title='개미와 베짱이', origin='이솝(공유 저작물)',
  cast=[('개미', '네모 엄마', 'lead', 'nemo'), ('베짱이', '세모 남편', 'funny', 'semo'), ('지켜보는 이웃', '동그라미 아빠', 'helper', 'dong')],
  line='여름에 곳간을 한 칸씩 채우는 개미, 겨울엔 노래만 남은 베짱이 — 개미는 곡식 한 줌과 「내년엔 같이」를 건넨다', kept=['여름에 일하는 개미 / 노는 베짱이', '겨울에 베짱이가 문을 두드림', '곳간 채우기'],
  cuts=[('더운 여름, 네모 엄마는 곡식을 나르고 세모 남편은 나무 그늘에서 노래만 불렀다.', ['nemo_mom.joy', 'husband.joy'], 'note'),
        ('개미는 곳간을 한 칸 한 칸 가득 채웠다. 칸이 다 찰 때마다 곳간이 환해졌다.', ['nemo_mom.joy', 'dong_dad.joy'], 'sparkle'),
        ('겨울이 오자 베짱이는 배가 고파 개미네 문을 똑똑 두드렸다.', ['husband.worry', 'nemo_mom.surprise'], 'question'),
        ('개미는 한숨을 쉬었지만 곡식 한 줌을 내밀었다. 「내년 여름엔 같이 일하자.」', ['nemo_mom.love', 'husband.love', 'dong_dad.joy'], 'heart')]),
 dict(base='sun', title='해님 달님', cast=None, cuts=[
  ('떡 팔러 간 엄마를 기다리던 오누이({kid1}·{kid2})는 문을 꼭 닫고 있었다.', ['nemo_kids.kid1', 'nemo_kids.kid2'], None),
  ('바람 호랑이가 엄마 목소리를 흉내 내며 찾아왔다. 「문 열어라.」 문틈의 손이 이상했다.', ['nemo_kids.kid1', 'nemo_kids.kid2'], 'question'),
  ('오누이는 뒷문으로 나가 나무 위로 올라갔다. 하늘에서 튼튼한 동아줄이 한 칸 한 칸 내려왔다.', ['nemo_kids.kid1', 'nemo_kids.kid2'], 'sparkle'),
  ('오누이는 동아줄을 타고 올라가 해님과 달님이 되었다. 바람 호랑이는 엉덩방아를 찧고 허허 웃었다.', ['nemo_kids.kid2', 'nemo_kids.kid1', 'nemo_mom.joy'], 'heart')]),
 dict(base='hare', title='토끼와 거북이', origin='이솝(공유 저작물)',
  cast=[('거북이', '네모 아빠', 'lead', 'nemo'), ('토끼', '세모 남편', 'funny', 'semo'), ('심판', '동그라미 아빠', 'helper', 'dong')],
  line='느림보 거북이가 한 칸씩 꾸준히, 낮잠 든 토끼(동그라미 아빠)는 웃으며 박수 — 심판은 세모 남편', kept=['토끼와 거북이의 경주', '토끼의 낮잠', '꾸준한 거북이의 승리'],
  cuts=[('토끼(동그라미 아빠)가 느림보 거북이(네모 아빠)에게 경주를 하자고 했다.', ['dong_dad.joy', 'nemo_dad.good'], 'question'),
        ('토끼는 쌩쌩 앞서 가다 그늘에서 낮잠. 거북이는 한 칸 한 칸 꾸준히 걸었다.', ['dong_dad.joy', 'nemo_dad.joy'], 'sparkle'),
        ('결승선 앞에서 눈을 뜬 토끼는 깜짝! 거북이는 이미 결승선에 닿아 있었다.', ['dong_dad.surprise', 'nemo_dad.love'], 'bang'),
        ('심판(세모 남편)이 손을 들어 올렸다. 토끼가 껄껄 웃으며 거북이에게 박수를 쳤다.', ['husband.joy', 'dong_dad.joy', 'nemo_dad.joy'], 'heart')]),
]
