// 짝 맞추기 sim: node tools/tile_sim.js — 20판 풀이 재생·종류 6+·연속 ≤3·곡선(탐욕 승률)·오늘의 한 판 30일·세 가족 규칙 3·가족 규칙 단언·섞기 후에도 풀림
const C = require('../games/tile/tile-core.js'), G = require('../games/tile/tile-gen.js'), D = require('../data/tile_levels.json');
let fails = 0; const ok = (c, m) => { console.log((c ? 'OK   ' : 'FAIL ') + m); if (!c) fails++; };
const replay = (L, rule) => { const S = C.newGame(L, rule); for (const i of L.solution) { const ev = C.press(S, i); if (!ev || ev.lose) return false; if (S.won) return true; } return S.won; };
ok(D.levels.length === 120 && D.levels.every((l) => replay(l)), '120판 풀이(제거 순서) 재생 모두 클리어');
const types = new Set(D.levels.map((l) => l.type)); ok(types.size >= 6, '판 종류 ' + types.size + '종: ' + [...types].join(','));
let run = 1, mx = 1; for (let i = 1; i < D.levels.length; i++) { run = D.levels[i].type === D.levels[i - 1].type ? run + 1 : 1; mx = Math.max(mx, run); } ok(mx <= 3, '같은 종류 연속 최대 ' + mx + '판(≤3)');
const rng = G.mulberry(5); console.log('--- 곡선(탐욕 사람 흉내 80회) ---'); console.log(' ' + D.levels.filter((l, i) => i % 6 === 0).map((l) => l.id + ':' + l.type + ' N' + l.tiles.length + ' ' + C.greedyWinRate(l, 60, rng).toFixed(2)).join(' | '));
const T = ['classic', 'goal', 'narrow', 'trio', 'lock', 'pair', 'classic']; let dOk = 0; for (let d = 0; d < 30; d++) { const L = G.make(8 + (d % 12), 20261000 + d, { type: T[d % 7], tag: 'growth', noGreedy: true }); if (L && replay(L)) dOk++; } ok(dOk === 30, '오늘의 한 판 30일 ' + dOk + '/30');
let tr = 0, trN = 0; for (let n = 6; n <= 14; n += 4) for (const rule of [0, 1, 2]) { trN++; const L = G.make(n, n * 6151 + 33, { type: 'classic', tag: 'growth', rule, noGreedy: true }); if (L && replay(L, rule)) tr++; } ok(tr === trN, '세 가족 규칙 판 ' + tr + '/' + trN);
// 규칙 단언
{ const L = { id: 0, type: 'classic', need: 3, cap: 7, goal: { t: 'all' }, tiles: [0, 1, 2, 3].map((i) => ({ x: i * 3, y: 0, z: 0, kind: i < 3 ? 'k0' : 'k1' })), solution: [0, 1, 2, 3] }, S = C.newGame(L); C.press(S, 3); C.press(S, 0); C.press(S, 1); ok(S.tray.length === 3 && S.tray[0].kind === 'k1' && C.press(S, 2).cleared[0] === 'k0' && S.tray.length === 1, '같은 그림 세 개가 모이면 사라지고 나머지는 바구니에 남음'); }
{ const L = { id: 0, type: 'classic', need: 3, cap: 7, goal: { t: 'all' }, tiles: [{ x: 0, y: 0, z: 0, kind: 'k0' }, { x: 1, y: 1, z: 1, kind: 'k1' }], solution: [1, 0] }, S = C.newGame(L); ok(!C.isFree(S, 0) && C.isFree(S, 1) && C.press(S, 0) === null, '위에 겹친 타일이 있으면 누를 수 없음'); }
{ const L = { id: 0, type: 'lock', need: 3, cap: 7, goal: { t: 'all' }, keyKind: 'key', tiles: [{ x: 0, y: 0, z: 0, kind: 'key' }, { x: 3, y: 0, z: 0, kind: 'key' }, { x: 6, y: 0, z: 0, kind: 'key' }, { x: 9, y: 0, z: 0, kind: 'k0', lock: true }], solution: [0, 1, 2, 3] }, S = C.newGame(L); ok(!C.isFree(S, 3), '자물쇠 타일은 열쇠 세 개를 지우기 전엔 눌리지 않음'); C.press(S, 0); C.press(S, 1); C.press(S, 2); ok(C.isFree(S, 3), '열쇠를 지우면 자물쇠가 풀림'); }
{ const L = { id: 0, type: 'classic', need: 3, cap: 3, goal: { t: 'all' }, tiles: [0, 1, 2, 3].map((i) => ({ x: i * 3, y: 0, z: 0, kind: 'k' + i })), solution: [0, 1, 2, 3] }, S = C.newGame(L); C.press(S, 0); C.press(S, 1); const ev = C.press(S, 2); ok(ev.lose && C.lost(S), '바구니가 가득 차면 졌다(벌 없이 한 번 더)'); }
{ const L = { id: 0, type: 'classic', need: 3, cap: 7, goal: { t: 'all' }, tiles: [0, 1, 2].map((i) => ({ x: i * 3, y: 0, z: 0, kind: 'k0' })), solution: [0, 1, 2] }, S = C.newGame(L, 0); ok(S.cap === 8, '네모 규칙: 바구니 8칸'); const L2 = { id: 0, type: 'classic', need: 3, cap: 7, goal: { t: 'all' }, tiles: [{ x: 0, y: 0, z: 0, kind: 'k0' }, { x: 3, y: 0, z: 0, kind: 'k0' }, { x: 6, y: 0, z: 0, kind: 'k1', wild: true }], solution: [0, 1, 2] }, S2 = C.newGame(L2, 1); C.press(S2, 0); C.press(S2, 1); const e2 = C.press(S2, 2); ok(e2.cleared.length === 1 && S2.won, '세모 규칙: 반짝 타일이 어떤 그림 대신이든 모자란 한 장을 채움'); const L3 = { id: 0, type: 'classic', need: 3, cap: 7, goal: { t: 'all' }, tiles: [{ x: 0, y: 0, z: 0, kind: 'k0' }, { x: 3, y: 0, z: 0, kind: 'k1' }, { x: 6, y: 0, z: 0, kind: 'k0' }, { x: 9, y: 0, z: 0, kind: 'k0' }], solution: [] }, S3 = C.newGame(L3, 2); C.press(S3, 0); C.press(S3, 1); C.press(S3, 2); const e3 = C.press(S3, 3); ok(e3.cleared.length === 0 && S3.tray.length === 4, '동그라미 규칙: 사이에 다른 그림이 끼면 나란히 세 개가 아니라 지워지지 않음'); }
{ const L = D.levels[10], S = C.newGame(L), rg = G.mulberry(3); C.press(S, L.solution[0]); C.press(S, L.solution[1]); const sh = C.shuffle(S, rg); let okp = sh, g = 0; if (sh) { for (const i of S.order || []) { const ev = C.press(S, i); if (!ev) { okp = false; break; } if (ev.lose) { okp = false; break; } if (S.won) break; g++; } } ok(sh && okp, '섞은 뒤에도 순서대로 누르면 풀림(레벨 11)'); }
console.log(fails ? 'FAILED ' + fails : 'ALL PASS'); process.exit(fails ? 1 : 0);
